# Site
name: "OFLS Blog"
baseurl: /blog
title: "Oxford Fintech & Legaltech Society Blog"
description: "Welcome to the Oxford Fintech & Legaltech Society Blog" 
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon-16x16.png'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://oxfordfss.us18.list-manage.com/subscribe?u=096c4257fd50892e3a2af1f28&id=f9f9cfb2d7'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  selina:
    name: Selina
    display_name: Selina
    avatar: 'assets/images/selina.png'
    description: "IT Officer of OFLS"
    linkedin: company/oxfordfls/
  dom:
    name: Domenico
    display_name: Domenico
    avatar: 'assets/images/dom.jpg'
    linkedin: in/domenico-piers-de-martino-753410148/
    description: "Domenico is a former President of the Oxford Fintech and Legaltech Society, and is an alumnus of the Masters in Law and Finance (2019)"
  daniel:
    name: Daniel
    display_name: Daniel
    avatar: 'assets/images/daniel.png'
    linkedin: in/daniel-goode-215258132/
    description: "Daniel is the Associate Editor at OFLS, and an MSc candidate in Law and Finance (2021) at the University of Oxford"
  melvin:
    name: Melvin
    display_name: Melvin  
    avatar: 'assets/images/melvin.jpg'
    linkedin: in/melvinobadha/
    description: "Melvin is a Fintech Researcher at OFLS, and a DPhil candidate in Health Economics (2022) at the University of Oxford."
  sampada:
    name: Sampada 
    display_name: Sampada  
    avatar: 'assets/images/sampada.jpg'
    linkedin: in/sampada-sudheesh-venkatesh-6241ab1b2/
    description: "Sampada is a Legal Researcher at OFLS, and a BA student in Law (2022) at the University of Oxford."
  shiyi:
    name: Shiyi
    display_name: Shiyi
    avatar: 'assets/images/shiyi.jpg'
    linkedin: in/shiyi-huang/
    description: "Shiyi is a former fintech researcher of OFLS and an alumnus of the Masters in Law and Finance (2019)"
  vaibhav:
    name: Vaibhav
    display_name: Vaibhav
    avatar: 'assets/images/vaibhav.jpg'
    linkedin: in/vaibhav-manchanda-18664b59/
    description: "Vaibhav is a former Associate Editor of OFLS (2019-2020). He received his BA in Law at the University of Oxford."
  irina:
    name: Irina
    display_name: Irina
    avatar: 'assets/images/irina.jpg'
    linkedin: in/irini-tsoutsou/
    description: "Irina is a former legaltech researcher of OFLS and an alumnus of the Masters in Law and Finance (2019)."
  sophia:
    name: Sophia
    display_name: Sophia
    avatar: 'assets/images/sophia.png'
    linkedin: in/sophia-chau-175b631a4/
    description: "Sophia is a Legaltech Researcher at OFLS, and an MSc student in Law and Finance (2020) at the University of Oxford"
  ofls:
    name: OFLS
    display_name: OFLS
    avatar: 'assets/images/logo-cube-small.jpg'
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    linkedin: company/oxfordfls/
    description: "This article was brought to you by the Oxford Fintech & Legaltech Society"
  alfonso:
    name: Alfonso
    display_name: Alfonso
    avatar: 'assets/images/alfonso.jpg'
    linkedin: in/alfonso-delgado-rius-82307483/
    description: "Alfonso founded OFLS (formerly FSS) in 2017. He is the Head of Research at Silver 8, and is an alumnus of the Masters in Law and Finance (2017)."
  oscar:
    name: Oscar Borgogno
    display_name: Oscar
    avatar: 'assets/images/oscar.jpg'
    linkedin: in/oscar-borgogno-1a089b107/
    description: "Oscar is a PhD Candidate, Law Department, University of Turin and an alumnus of the Masters in Law and Finance (2019) at the University of Oxford. He is also a Law & Digital Integration Expert at the Bank of Italy."
  external:
    name: External contribution
    display_name: External
    avatar: 'assets/images/logo-cube-small.jpg'
    linkedin: company/oxfordfls/
  Daniel Foa:
    name: Daniel Foa
    display_name: Daniel Foa
    avatar: 'assets/images/danielfoa.jpeg'
    linkedin: in/daniel-foà-b7b37a13a/
    description: "Daniel holds a  Ph.D. in Law and Business at LUISS Guido Carli (Rome) and is an MSc. Candidate in Law and Finance at University of Oxford (F. Bonelli Scholar)"
  Dimitrios:
    name: Dimitrios Kyriazis
    display_name: Dr. Dimitrios Kyriazis
    avatar: 'assets/images/dimitrios.jpg'
    linkedin: in/dimitrios-kyriazis-60ab2259/
    description: "Dimitrios (DPhil, Oxon) is a state aid lawyer and a Research Fellow in Law at the New College of the Humanities, where from 2017 to 2020 he served as Head of the Law Faculty. He was previously a Lecturer in Law at Oxford University and a Teaching Fellow in Law at UCL."
  Ashika Jain:
    name: Ashika Jain
    display_name: Ashika Jain
    avatar: 
    linkedin: in/ashika-jain-b7633619/
    description: "Ashika is a student at the WB National University of Juridical Sciences, India, and a Senior Associate Member of the NUJS Law Review. She represented NUJS at the 27th Willem C. Vis International Commercial Arbitration Moot, 2020 where they were adjudged the winners and awarded the Eric E. Bergsten award for the Best Team Orals."
  Rani Subassandran:
    name: Rani Subassandran
    display_name: Rani Subassandran
    avatar: 'assets/images/Rani1.jpg'
    linkedin: in/rani-subassandran-b836241a/
    description: "Rani is an external contributor to OFLS, and is an University of Oxford alumnus of the Bachelor of Civil Law (2011)"
  Zenon Hadjicostas:
    name: Zenon Hadjicostas
    display_name: Zenon Hadjicostas
    avatar: 'assets/images/Zenon Hadjicostas.jpg' 
    linkedin: in/zenonhadjicostas-589264158/
    description: "Zenon is a Legaltech Researcher at OFLS, and an MSc student in Law and Finance (2022) at the University of Oxford"  
  Arnav Maru:
    name: Arnav Maru
    display_name: Arnav Maru
    avatar: 'assets/images/Arnav Maru.jpg'
    linkedin: in/arnavmaru/
    description: "Arnav is a Legaltech Researcher at OFLS, and an MSc student in Law and Finance (2022) at the University of Oxford"
  Maxwell Smith:
    name: Maxwell Smith
    display_name: Maxwell Smith
    avatar: 'assets/images/Maxwell Smith.jpg'
    linkedin: in/maxwellsmith/
    description: "Max is the President of OFLS 2021/2022, and an MSc student in Law and Finance (2022) at the University of Oxford"
  Gabriel Araújo Souto:
    name: Gabriel Araújo Souto
    display_name: Gabriel Araújo Souto
    avatar: 'assets/images/Gabriel Araujo Souto - Photo.jpeg'
    linkedin: in/gasouto/
    description: "Gabriel is a Council member at the Brazilian Laboratory of Public Policy and Internet (LAPIN) and a Researcher at the Brazilian Chamber of Deputies" 
    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
