# Site
name: "OFLS"
title: "Oxford Fintech & Legaltech Society Blog"
description: "Welcome to the Oxford Fintech & Legaltech Society Blog"
logo: '/assets/images/logo-cube.jpg'
favicon: '/assets/images/favicon-16x16.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://oxfordfss.us18.list-manage.com/subscribe?u=096c4257fd50892e3a2af1f28&id=f9f9cfb2d7'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  selina:
    name: Selina
    display_name: Selina
    avatar: 'assets/images/selina.png'
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "IT Officer of OFLS"
  dom:
    name: Domenico
    display_name: Domenico
    avatar: 'assets/images/dom.jpg'
    web: https://www.linkedin.com/in/domenico-piers-de-martino-753410148/
    twitter: https://twitter.com/oxfordFLS
    description: "Domenico is a former President of the Oxford Fintech and Legaltech Society. He is currently a Research Assistant at the University of Oxford and is an alumnus of the Masters in Law and Finance (2019)"
  daniel:
    name: Daniel
    display_name: Daniel
    avatar: 'assets/images/daniel.jpg'
    web: https://www.linkedin.com/in/daniel-goode-215258132/
    twitter: https://twitter.com/oxfordFLS
    description: "Daniel is an Associate Editor at OFLS, and a MSc candidate in Law and Finance (2021) at the University of Oxford"
  melvin:
    name: Melvin
    display_name: Melvin  
    avatar: 'assets/images/melvin.jpg'
    web: https://www.linkedin.com/in/melvinobadha/
    twitter: https://twitter.com/oxfordFLS
    description: "Melvin is a Fintech Researcher at OFLS, and a DPhil candidate in Health Economics (2022) at the University of Oxford."
  sampada:
    name: Sampada 
    display_name: Sampada  
    avatar: 'assets/images/sampada.jpg'
    web: https://www.linkedin.com/in/sampada-sudheesh-venkatesh-6241ab1b2/
    twitter: https://twitter.com/oxfordFLS
    description: "Sampada is a Legal Researcher at OFLS, and a BA student in Law (2022) at the University of Oxford."
  shiyi:
    name: Shiyi
    display_name: Shiyi
    avatar: 'assets/images/shiyi.jpg'
    web: https://www.linkedin.com/in/shiyi-huang/
    twitter: https://twitter.com/oxfordFLS
    description: "Shiyi is a former fintech researcher of OFLS and an alumnus of the Masters in Law and Finance (2019)"
  vaibhav:
    name: Vaibhav
    display_name: Vaibhav
    avatar: 'assets/images/vaibhav.jpg'
    web: https://www.linkedin.com/in/vaibhav-manchanda-18664b59/
    twitter: https://twitter.com/oxfordFLS
    description: "Vaibhav is a former Associate Editor of OFLS (2019-2020). He received his BA in Law at the University of Oxford."
  irina:
    name: Irina
    display_name: Irina
    avatar: 'assets/images/irina.jpg'
    web: https://www.linkedin.com/in/irini-tsoutsou/
    twitter: https://twitter.com/oxfordFLS
    description: "Irina is a former legaltech researcher of OFLS and an alumnus of the Masters in Law and Finance (2019)."
  sophia:
    name: Sophia
    display_name: Sophia
    avatar: 'assets/images/sophia.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    web: https://www.linkedin.com/in/sophia-chau-175b631a4/)_is
    twitter: https://twitter.com/oxfordFLS
    description: "Sophia is a Legaltech Researcher at OFLS, and an MSc student in Law and Finance (2020) at the University of Oxford"
  ofls:
    name: OFLS
    display_name: OFLS
    avatar: 'assets/images/logo-cube-small.jpg'
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "This article was brought to you by the Oxford Fintech & Legaltech Society"
  alfonso:
    name: Alfonso
    display_name: Alfonso
    avatar: 'assets/images/alfonso.jpg'
    web: https://www.linkedin.com/in/alfonso-delgado-rius-82307483/
    twitter: https://twitter.com/oxfordFLS
    description: "Alfonso founded OFLS (formerly FSS) in 2017. He is the Head of Research at Silver 8, and is an alumnus of the Masters in Law and Finance (2017)."
  oscar:
    name: Oscar Borgogno
    display_name: Oscar
    avatar: 'assets/images/oscar.jpg'
    web: https://www.linkedin.com/in/oscar-borgogno-1a089b107/
    linkedin: oscar-borgogno-1a089b107/
    description: "Oscar is a PhD Candidate, Law Department, University of Turin and an alumnus of the Masters in Law and Finance (2019) at the University of Oxford. He is also a Law & Digital Integration Expert at the Bank of Italy."
  external:
    name: External contribution
    display_name: External
    avatar: 'assets/images/logo-cube-small.jpg'

    
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
