# Site
name: "OFLS"
title: "Oxford Fintech & Legaltech Society Blog"
description: "Welcome to the Oxford Fintech & Legaltech Society Blog"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.png'
baseurl: 
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://oxfordfss.us18.list-manage.com/subscribe?u=096c4257fd50892e3a2af1f28&id=f9f9cfb2d7'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Selina
    display_name: Selina
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "IT Officer of OFLS"
  john:
    name: Domenico
    display_name: Dom   
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Ex-president of OFLS 2019"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
