# Site
name: "OFLS"
title: "Oxford Fintech & Legaltech Society Blog"
description: "Welcome to the Oxford Fintech & Legaltech Society Blog"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.png'
baseurl: 'oxfordfls.github.io/'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://oxfordfss.us18.list-manage.com/subscribe?u=096c4257fd50892e3a2af1f28&id=f9f9cfb2d7'

include: ["_pages"]
permalink: /:title/

# Authors
authors:
  selina:
    name: Selina
    display_name: Selina
    avatar: 'assets/images/avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "IT Officer of OFLS"
  dom:
    name: Domenico
    display_name: Domenico
    avatar: 'assets/images/dom.jpeg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Ex-president of OFLS 2019"
  daniel:
    name: Daniel
    display_name: Daniel
    avatar: 'assets/images/daniel.jpg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Associate Editor at OFLS"
  melvin:
    name: Melvin
    display_name: Melvin  
    avatar: 'assets/images/melvin.jpeg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Fintech researcher at OFLS"
  sampada:
    name: Sampada 
    display_name: Sampada  
    avatar: 'assets/images/sampada.jpeg'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "A Legal Researcher at OFLS, and a BA student in Law (2022), University of Oxford"
  shiyi:
    name: Shiyi
    display_name: Shiyi
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Former fintech researcher of OFLS and a graduate of MSc Law and Finance (2019)"
  vaibhav:
    name: Vaibhav
    display_name: Vaibhav
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Former Associate Editor of OFLS (2019-2020)"
  irina:
    name: Irina
    display_name: Irina
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Former legaltech researcher of OFLS and a graduate of MSc Law and Finance (2019)"
  sophia:
    name: Sophia
    display_name: Sophia
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: contact@oxfordfls.org
    web: https://oxfordfls.org
    twitter: https://twitter.com/oxfordFLS
    description: "Legaltech researcher at OFLS"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
